runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 100

service:
  upload

readiness_check:
  path: /readiness_check
  app_start_timeout_sec: 300

manual_scaling:
  instances: 2

